;;Setup lib directories
(setq lib-dir "~/lib/emacs/")
(setq etc-dir "~/etc/emacs/") 
(setq var-dir "~/var/emacs/")
    
(let ((default-directory lib-dir))
      (normal-top-level-add-to-load-path '("."))
      (normal-top-level-add-subdirs-to-load-path))

(setq autoload-file (concat etc-dir "loaddefs.el"))
(setq custom-file (concat etc-dir "custom.el"))

(defun configure (path) (load-file (concat etc-dir path ".el")))

(configure "nogui")
(configure "backups")
(configure "package")
(configure "linum")
(configure "theme")
(configure "fci-mode")
(configure "mail")
(configure "jabber")
(configure "search")
(configure "nav")
(configure "autocomplete")
(configure "indent")
(configure "dvorak")
(configure "yasnippet")
(configure "perl")
(configure "scala")
(configure "haskell")
(configure "autosave")
(configure "org")
(configure "filemenu")
(configure "misc")
(configure "yaml")
(configure "write-date")
(configure "latex")

